#!/bin/bash

# Install Dependencies
sudo dnf install -y mariadb105-server
sudo dnf install -y java-11-amazon-corretto
sudo dnf install -y java-11-amazon-corretto-devel
sudo dnf install -y expect
sudo dnf install -y stress

# Autostarting MariaDB
sudo systemctl enable mariadb && sudo systemctl start mariadb

# Setup MariaDB
wget https://raw.githubusercontent.com/patrickpulfer/Athlon/main/amazon_ec2_mariadb_setup.sh
chmod +x amazon_ec2_mariadb_setup.sh
sudo sh ./amazon_ec2_mariadb_setup.sh

# Setup initial SQL tables
wget https://raw.githubusercontent.com/patrickpulfer/Athlon/main/amazon_ec2_setup_sql.sql
sudo mysql --user=root --password=test1234 < amazon_ec2_setup_sql.sql

# Setup Coupon Service
wget https://testathlon.s3.eu-north-1.amazonaws.com/couponservice-0.0.1-SNAPSHOT.jar
sudo cp couponservice-0.0.1-SNAPSHOT.jar /usr/local/bin

# Setup AutoLaunch Script
echo '#!/bin/bash' | sudo tee -a /usr/local/bin/autolaunch.sh
echo 'java -jar /usr/local/bin/couponservice-0.0.1-SNAPSHOT.jar' | sudo tee -a /usr/local/bin/autolaunch.sh
sudo chmod +x /usr/local/bin/autolaunch.sh

# Setup AutoLaunch SystemD Service
echo '[Unit]' | sudo tee -a /etc/systemd/system/coupon_service.service
echo 'Description=CouponService' | sudo tee -a /etc/systemd/system/coupon_service.service
echo '[Service]' | sudo tee -a /etc/systemd/system/coupon_service.service
echo 'Type=simple' | sudo tee -a /etc/systemd/system/coupon_service.service
echo 'ExecStart=/usr/local/bin/autolaunch.sh' | sudo tee -a /etc/systemd/system/coupon_service.service
echo '[Install]' | sudo tee -a /etc/systemd/system/coupon_service.service
echo 'WantedBy=multi-user.target' | sudo tee -a /etc/systemd/system/coupon_service.service
sudo systemctl enable coupon_service && sudo systemctl start coupon_service

